name: "Pull Request Labeler"
on:
  pull_request:
    branches: main

permissions:
   pull-requests: write
   contents: read

jobs:
  triage:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
